# Generated by Django 4.1.1 on 2022-09-13 07:45

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_detail', models.TextField(blank=True, null=True)),
                ('content', froala_editor.fields.FroalaField(blank=True, null=True)),
            ],
        ),
    ]
