# Generated by Django 4.1.1 on 2022-09-13 11:53

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cfroala', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_detail', models.TextField(blank=True, null=True)),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
    ]
