# Generated by Django 4.1.1 on 2022-09-13 12:40

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cfroala', '0002_tinypost'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinypost',
            name='document',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='PDF'),
        ),
    ]
